---
- hosts: yalink-dev
  become: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: data/data.sql
        dest: /tmp/data.sql
        mode: "0777"

    - name: Create db user
      community.postgresql.postgresql_user:
        state: present
        name: yalink
        password: yalink123
      become: yes
      become_user: postgres

    - name: Create database
      community.postgresql.postgresql_db:
        state: present
        owner: yalink
        name: "{{ db_base_name }}.{{ item.name }}"
      become: yes
      become_user: postgres
      loop: "{{ users }}"

    - name: Restore data in database
      community.postgresql.postgresql_db:
        state: restore
        target: /tmp/data.sql
        name: "{{ db_base_name }}.{{ item.name }}"
      become: yes
      become_user: postgres
      loop: "{{ users }}"
