---
- hosts: yalink-dev
  become: yes
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - group: name=sudo state=present

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers users to wheel group
    user:
      name: "{{ item.username }}" 
      groups: wheel
      append: yes
      state: present
      createhome: yes
    loop: "{{ dev_users}}"

  - name: Set up authorized keys for the deployer user
    authorized_key: 
      user: "{{ item.username }}"
      key: "{{ lookup('file', 'data/authorized_keys') }}"
    loop: "{{ dev_users}}"
  
  - name: Install python3 venv to have separate python envs per user
    ansible.builtin.apt:
      name: python3-venv
      state: present
